"""Response schemas for the Architecture APIs.

These expose the EXISTING repository graph (nodes / edges / repo_files) — no new
graph structures, no AI, no LLM.
"""

from pydantic import BaseModel


class ArchitectureOverview(BaseModel):
    frontend_components: int
    backend_services: int
    api_routes: int
    database_tables: int
    classes: int
    functions: int
    external_apis: int
    total_files: int
    total_dependencies: int


class ArchNodeSummary(BaseModel):
    id: str
    name: str
    node_type: str
    full_path: str
    file_path: str | None = None
    language: str | None = None
    http_method: str | None = None
    route_path: str | None = None
    is_exported: bool = False
    is_async: bool = False
    start_line: int | None = None
    end_line: int | None = None


class RelatedNode(ArchNodeSummary):
    """A node reached through an edge; `edge_type` is the relationship."""

    edge_type: str | None = None


class ComponentGroup(BaseModel):
    key: str
    label: str
    count: int
    items: list[ArchNodeSummary]


class ArchitectureComponents(BaseModel):
    repo_id: str
    groups: list[ComponentGroup]


class NodeDetails(BaseModel):
    node: ArchNodeSummary
    file_path: str | None = None
    callers: list[ArchNodeSummary]
    callees: list[ArchNodeSummary]
    services: list[ArchNodeSummary]
    tables: list[RelatedNode]
    dependencies: list[RelatedNode]


class DependencyEdge(BaseModel):
    from_node_id: str
    from_name: str
    to_node_id: str
    to_name: str
    edge_type: str


class ArchitectureDependencies(BaseModel):
    repo_id: str
    total_edges: int
    edge_type_counts: dict[str, int]
    edges: list[DependencyEdge]


# ── Architecture Explainer ────────────────────────────────────────────
# These power GET /architecture/explain/{node_id} and
# GET /architecture/explain-flow/{flow_id}. The narrative prose is generated by
# Groq, but EVERY field is grounded in graph evidence: the explainer hands the
# model only structured facts pulled from nodes / edges / flows and forbids it
# from inventing anything. `evidence` echoes back the exact graph facts used so
# the output is auditable.


class RelatedComponent(BaseModel):
    """A graph neighbour offered as a related component for navigation."""

    id: str
    name: str
    node_type: str
    relationship: str  # e.g. "caller", "callee", "service", "table", "import"


class ExplanationEvidence(BaseModel):
    """The raw graph facts the explanation was built from — fully auditable.

    If the LLM is unavailable the deterministic fallback is assembled purely
    from these same facts, so nothing here is ever invented.
    """

    subject_kind: str  # "node" | "flow"
    node_type: str | None = None
    flow_type: str | None = None
    file_path: str | None = None
    http_method: str | None = None
    route_path: str | None = None
    caller_names: list[str] = []
    callee_names: list[str] = []
    service_names: list[str] = []
    table_relations: list[str] = []  # "reads_table:users"
    dependency_relations: list[str] = []  # "imports:foo"
    import_names: list[str] = []
    flow_step_count: int | None = None
    flow_node_count: int | None = None
    critical_node_names: list[str] = []
    # Raw counts the scores are derived from (auditable inputs to the analytics).
    caller_count: int = 0
    callee_count: int = 0
    dependency_count: int = 0
    table_count: int = 0
    api_count: int = 0
    centrality_score: float | None = None  # 0–100 from impact_metrics, if precomputed
    llm_used: bool = False


class ImpactIfChanged(BaseModel):
    """What breaks if the subject is changed — derived from incident graph edges."""

    callers_affected: int
    callers_breaking: list[str]
    apis_affected: list[str]
    services_affected: list[str]
    database_tables_affected: list[str]
    summary: str


class MetricFactor(BaseModel):
    """One contributing input to a score, kept for auditability."""

    label: str
    value: float
    detail: str


class ArchitectureExplanation(BaseModel):
    """Natural-language architecture explanation grounded in graph evidence.

    Prose fields (title/summary/purpose/responsibilities/…) may be written by
    Groq from graph facts. The analytics fields (architecture_health,
    complexity_score, coupling_score, risk_level, impact_if_changed) are computed
    DETERMINISTICALLY in Python from graph evidence only — the LLM never produces
    a number or a verdict. `recommendations` are rule-derived; the LLM may only
    rephrase, never add.
    """

    repo_id: str
    subject_id: str  # node_id or flow_id
    subject_kind: str  # "node" | "flow"
    title: str
    summary: str
    purpose: str
    responsibilities: list[str]
    inputs: list[str]
    outputs: list[str]
    dependencies: list[str]
    risks: list[str]
    related_components: list[RelatedComponent]

    # ── Analytics (deterministic, graph-derived) ──────────────────────
    architecture_health: str  # "Healthy" | "Moderate Risk" | "High Risk"
    complexity_score: int  # 1–10
    coupling_score: int  # 1–10
    risk_level: str  # "Low" | "Medium" | "High"
    impact_if_changed: ImpactIfChanged
    recommendations: list[str]
    score_factors: list[MetricFactor]  # audit trail for the scores

    evidence: ExplanationEvidence


class Hotspot(BaseModel):
    node_id: str
    node_name: str
    risk_level: str
    reason: str


class ArchitectureHealthReport(BaseModel):
    overall_score: int
    architecture_health: str
    complexity_score: int
    coupling_score: int
    maintainability_score: int
    risk_score: int
    hotspots: list[Hotspot]
    recommendations: list[str]


class StoryChapter(BaseModel):
    title: str
    content: str
    related_nodes: list[str]
    related_flows: list[str]


class ArchitectureStory(BaseModel):
    repository_summary: str
    chapters: list[StoryChapter]
