from typing import Dict, Optional
from datetime import datetime
from pydantic import BaseModel, Field

from app.schemas.intent import IntentClassificationResponse
from app.services.engineering_evidence.models import EngineeringEvidence
from app.schemas.impact_analysis import ImpactAnalysisResponse
from app.schemas.recommendation import RecommendationResponse


class EngineeringReport(BaseModel):
    """
    Comprehensive Engineering Report generated by the AI Change Intelligence Pipeline.
    Encapsulates all analytical stages from initial intent to final recommendations.
    """
    
    question: str = Field(..., description="The original developer question or prompt")
    timestamp: datetime = Field(default_factory=datetime.utcnow, description="When the report was generated")
    
    intent: IntentClassificationResponse = Field(..., description="Parsed intent and entity extraction")
    evidence: Optional[EngineeringEvidence] = Field(None, description="Engineering evidence collected for the analysis")
    impact: Optional[ImpactAnalysisResponse] = Field(None, description="Deterministic impact and blast radius")
    recommendations: Optional[RecommendationResponse] = Field(None, description="Actionable engineering recommendations")
    
    execution_metrics: Dict[str, float] = Field(
        default_factory=dict, 
        description="Timing and performance metrics for each pipeline phase in milliseconds"
    )
