"""
Graph Query Engine Errors Package.
"""

from graph_query_engine.errors.codes import ErrorCode
from graph_query_engine.errors.exceptions import (
    BudgetExceededError,
    CSRConstructionError,
    CapabilityUnsupportedError,
    ConfigurationError,
    DanglingEdgeError,
    DuplicateEdgeError,
    DuplicateNodeError,
    DuplicateQualifiedNameError,
    DuplicateRouteError,
    DuplicateSymbolError,
    EngineNotImplementedError as NotImplementedError,
    ExecutionError,
    GraphQueryEngineError,
    GraphQueryError,
    ImmutabilityError,
    IndexBuildError,
    IndexLookupError,
    InitializationError,
    InvalidPlannerConfigError,
    InvalidPlannerStateError,
    LifecycleError,
    PlannerError,
    PlannerRegistryError,
    RelationshipLookupError,
    SemanticIndexError,
    TimeoutError,
    ValidationError,
)

__all__ = [
    "ErrorCode",
    "GraphQueryEngineError",
    "GraphQueryError",
    "ConfigurationError",
    "ValidationError",
    "ImmutabilityError",
    "LifecycleError",
    "InitializationError",
    "ExecutionError",
    "TimeoutError",
    "NotImplementedError",
    "DuplicateNodeError",
    "DuplicateEdgeError",
    "DuplicateSymbolError",
    "DuplicateQualifiedNameError",
    "IndexBuildError",
    "IndexLookupError",
    "DanglingEdgeError",
    "CSRConstructionError",
    "RelationshipLookupError",
    "SemanticIndexError",
    "DuplicateRouteError",
    "PlannerError",
    "InvalidPlannerStateError",
    "BudgetExceededError",
    "InvalidPlannerConfigError",
    "PlannerRegistryError",
    "CapabilityUnsupportedError",
]
