"""
Graph Query Engine Error Framework Package.
"""

from graph_query_engine.errors.base import GraphQueryError
from graph_query_engine.errors.codes import ErrorCode
from graph_query_engine.errors.exceptions import (
    BrokenReferenceError,
    CSRConstructionError,
    ConfigurationError,
    DanglingEdgeError,
    DuplicateDefinitionError,
    DuplicateEdgeError,
    DuplicateNodeError,
    DuplicateQualifiedNameError,
    DuplicateRouteError,
    DuplicateSymbolError,
    ExecutionError,
    FeatureNotImplementedError,
    IndexBuildError,
    IndexLookupError,
    InitializationError,
    InvalidAnnotationError,
    InvalidImportError,
    InvalidInheritanceError,
    InvalidRelationshipError,
    MissingInterfaceError,
    MissingParentTypeError,
    NotImplementedError,
    RelationshipIntegrityError,
    RelationshipLookupError,
    SemanticIndexError,
    TimeoutError,
    ValidationError,
)

__all__ = [
    "ErrorCode",
    "GraphQueryError",
    "InitializationError",
    "ConfigurationError",
    "ValidationError",
    "ExecutionError",
    "TimeoutError",
    "FeatureNotImplementedError",
    "NotImplementedError",
    "IndexBuildError",
    "IndexLookupError",
    "DuplicateNodeError",
    "DuplicateEdgeError",
    "DuplicateSymbolError",
    "DuplicateQualifiedNameError",
    "InvalidRelationshipError",
    "DanglingEdgeError",
    "RelationshipIntegrityError",
    "CSRConstructionError",
    "RelationshipLookupError",
    "SemanticIndexError",
    "InvalidInheritanceError",
    "DuplicateRouteError",
    "BrokenReferenceError",
    "InvalidImportError",
    "InvalidAnnotationError",
    "MissingInterfaceError",
    "MissingParentTypeError",
    "DuplicateDefinitionError",
]
