"""
Centralized Error Codes for Graph Query Engine.
"""

from enum import StrEnum


class ErrorCode(StrEnum):
    """
    Standardized unique error codes for the Graph Query Engine.
    """
    GENERIC_ERROR = "ERR_GQE_000"
    INITIALIZATION_FAILED = "ERR_GQE_INIT_001"
    CONFIGURATION_INVALID = "ERR_GQE_CFG_001"
    VALIDATION_FAILED = "ERR_GQE_VAL_001"
    EXECUTION_FAILED = "ERR_GQE_EXEC_001"
    TIMEOUT_EXCEEDED = "ERR_GQE_TIMEOUT_001"
    NOT_IMPLEMENTED = "ERR_GQE_NOT_IMPL_001"
    RESOURCE_LIMIT_EXCEEDED = "ERR_GQE_RES_001"
    INVALID_QUERY_SYNTAX = "ERR_GQE_SYNTAX_001"
    SNAPSHOT_NOT_FOUND = "ERR_GQE_SNAPSHOT_001"

    # Step 3.2 Index Error Codes
    DUPLICATE_NODE_ID = "ERR_GQE_IDX_DUP_NODE_001"
    DUPLICATE_EDGE_ID = "ERR_GQE_IDX_DUP_EDGE_001"
    DUPLICATE_SYMBOL_ID = "ERR_GQE_IDX_DUP_SYM_001"
    DUPLICATE_QUALIFIED_NAME = "ERR_GQE_IDX_DUP_QUAL_001"
    INDEX_BUILD_FAILED = "ERR_GQE_IDX_BUILD_001"
    INDEX_LOOKUP_FAILED = "ERR_GQE_IDX_LOOKUP_001"

    # Step 3.3 Relationship Index Error Codes
    INVALID_RELATIONSHIP = "ERR_GQE_IDX_INVALID_REL_001"
    DANGLING_EDGE = "ERR_GQE_IDX_DANGLING_EDGE_001"
    RELATIONSHIP_INTEGRITY_FAILED = "ERR_GQE_IDX_REL_INTEGRITY_001"
    CSR_CONSTRUCTION_FAILED = "ERR_GQE_IDX_CSR_CONST_001"
    RELATIONSHIP_LOOKUP_FAILED = "ERR_GQE_IDX_REL_LOOKUP_001"

    # Step 3.4 Semantic Index Error Codes
    SEMANTIC_INDEX_FAILED = "ERR_GQE_IDX_SEM_001"
    INVALID_INHERITANCE = "ERR_GQE_IDX_INVALID_INH_001"
    DUPLICATE_ROUTE = "ERR_GQE_IDX_DUP_ROUTE_001"
    BROKEN_REFERENCE = "ERR_GQE_IDX_BROKEN_REF_001"
    INVALID_IMPORT = "ERR_GQE_IDX_INVALID_IMP_001"
    INVALID_ANNOTATION = "ERR_GQE_IDX_INVALID_ANN_001"
    MISSING_INTERFACE = "ERR_GQE_IDX_MISSING_IFACE_001"
    MISSING_PARENT_TYPE = "ERR_GQE_IDX_MISSING_PARENT_001"
    DUPLICATE_DEFINITION = "ERR_GQE_IDX_DUP_DEF_001"


__all__ = ["ErrorCode"]
